### ISSUE TITLE
Using parameterized variables in Forrest::query

### ISSUE THREAD

**Issue by blorange2** [omniphx/forrest#193]
In an application I'm working on we use the LIKE operator to check for similar companies, like so:

```
//Search salesforce for similar / identical company names
$findCo = "SELECT Name, Id FROM Account WHERE Name LIKE '%".$name."%'";

//Return results of above to select box
$findCo =  Forrest::query( $findCo );
```

However, In the code above there is an injection vulnerability, and anything entered with an apostrophe will blow up,  what is the best way around this?

**Comment by omniphx** [comment]
What do you mean by blow up?

**Comment by blorange2** [comment]
Sorry, the string will be closed by the apostrophe and the SQL statement will be malformed, causing a server error.

**Comment by omniphx** [comment]
Do you mind posting the error message as well?

Wondering if this has something to do with the URL encoding of the "%"  character: https://github.com/omniphx/forrest/blob/4df61dc29b339be42fb50e37179bf3d3786ff8c6/src/Omniphx/Forrest/Client.php#L424

**Comment by blorange2** [comment]
Hi again,

See below:

```
[{\"message\":\"\
Account WHERE Name LIKE '%Dalston's%'\
                                 ^\
ERROR at Row:1:Column:55\
unex (truncated...)
 at /homepages/45/d641872465/htdocs/events/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]
#0 /homepages/45/d641872465/htdocs/events/vendor/omniphx/forrest/src/Omniphx/Forrest/Client.php(199): Omniphx\\Forrest\\Client->assignExceptions(Object(GuzzleHttp\\Exception\\ClientException))
#1 /homepages/45/d641872465/htdocs/events/vendor/omniphx/forrest/src/Omniphx/Forrest/Client.php(180): Omniphx\\Forrest\\Client->handleRequest()
#2 /homepages/45/d641872465/htdocs/events/vendor/omniphx/forrest/src/Omniphx/Forrest/Client.php(426): Omniphx\\Forrest\\Client->request('https://newable...', Array)
#3 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Omniphx\\Forrest\\Client->query('SELECT Name, Id...')
#4 /homepages/45/d641872465/htdocs/events/app/Http/Controllers/CampaignController.php(177): Illuminate\\Support\\Facades\\Facade::__callStatic('query', Array)
#5 [internal function]: App\\Http\\Controllers\\CampaignController->findAccountName(Object(Illuminate\\Http\\Request))
#6 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#7 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('findAccountName', Array)
#8 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\CampaignController), 'findAccountName')
#9 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#10 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
#11 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#33 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#34 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#35 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#36 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#37 /homepages/45/d641872465/htdocs/events/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /homepages/45/d641872465/htdocs/events/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#55 /homepages/45/d641872465/htdocs/events/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#56 {main}
"} 
```

**Comment by omniphx** [comment]
Looks like there's an unescaped single quote: `Account WHERE Name LIKE '%Dalston's%'` 

Which should be `SELECT Id FROM Account WHERE Name LIKE '%Dalston\'s%'`

Maybe try `addSlashes($name)` or something similar
